api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('products/', views.ProductList.as_view()),
    path('product/<int:pk>/', views.ProductDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

unimed/urls.py
from django.contrib import admin
from django.urls import path, include
from telegram_bot.views import worker
from django.conf import settings

urlpatterns = [
    path('api/', include('api.urls')),
    path('webbot/', include('webbot.urls')),
    path('admin/', admin.site.urls),
    path(f'telegram/{settings.TOKEN}/', worker, name="bot"),
    path('', include('website.urls')),
    
]

website/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from website import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('search/', views.ProductList, name='search'),

    path('category/', views.CategoryListPage.as_view(), name='category-list'),
    path('categories/<slug:slug>/', views.CategoryDetailPage.as_view(), name='category-detail'),
    path('products/<slug:slug>/', views.ProductDetailPage.as_view(), name='product-detail'),
    path('products/<slug:slug>/order/', views.ProductOrderPage.as_view(), name='product-order'),
    path('contactRequest/', views.ContactRequestFormHandler.as_view(), name='contact-request'),
    path('orderSuccess/', views.OrderSuccessPage.as_view(), name='order-success'),
    path('contactRequestSuccess/', views.OrderSuccessPage.as_view(), name='contact-request-success'),
    path('cooperate/', views.Cooperate, name='cooperate'),
    path('send_marketing/', views.Markettingmessage),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from core import constants
from core.constants import ClientTypeEnum
import random
from django.db.models.signals import pre_save


class ParentCategory(models.Model):
    name = models.CharField(max_length=255, unique=True,
                            verbose_name=_('Название'))
    slug = models.SlugField(verbose_name=_('Человекочитаемый идентификатор'))
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Родительская категория')
        verbose_name_plural = _('Родительские категории')


class Category(models.Model):
    parent = models.ForeignKey(ParentCategory, on_delete=models.CASCADE, related_name='child_categories')
    name = models.CharField(max_length=255, unique=True,
                            verbose_name=_('Название'))
    slug = models.SlugField(verbose_name=_('Человекочитаемый идентификатор'))
    def __str__(self):
        return self.name
    class Meta:

        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

class ProductManufacturer(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('Название бренда'))
    def __str__(self):
        return self.name

    class Meta:

        verbose_name = _('Производитель')
        verbose_name_plural = _('Производители')


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products',
                                 verbose_name=_('Принадлежит категории'))
    manufacturer = models.ForeignKey(ProductManufacturer, on_delete=models.CASCADE, related_name='products', verbose_name=_('Производитель'))
    name = models.CharField(max_length=255, unique=True,
                            verbose_name=_('Название (короткое)'))
    partner = models.CharField(max_length=25, default='Unimed',
                            verbose_name=_('Партнер'))
    name_search = models.CharField(max_length=400, unique=True, default='Нет',
                            verbose_name=_('Название для поиска (длинное)'))
    slug = models.SlugField(verbose_name=_('Человекочитаемый идентификатор'))
    short_description = models.TextField(verbose_name=_('Короткое описание'), blank=True)
    long_description = models.TextField(verbose_name=_('Общее описание'), blank=True)
    technical_details = models.TextField(
        verbose_name=_('Технические характеристики'), blank=True)
    brochure = models.FileField(
        upload_to='product_brochures', verbose_name=_('Брошюра'), blank=True, null=True)
    standard_of_equipment = models.FileField(upload_to='product_standards_of_equipment',
                                             verbose_name=_('Стандарт оснащения'), blank=True, null=True)
    commercial_proposal_file = models.FileField(
        upload_to='commercial_proposals', verbose_name=_('Файл КП'), blank=True, null=True)
    is_used = models.BooleanField(default=True, verbose_name="БУ")
    

    def __str__(self):
        return self.name

    class Meta:

        verbose_name = _('Товар')
        verbose_name_plural = _('Товары')


class ProductImage(models.Model):
    belongs_to = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images',
                                   verbose_name=_('Принадлежит продукту'))
    image_file = models.ImageField(
        upload_to='product_images', verbose_name=_('Изображение продукта'))

    def __str__(self):
        return self.image_file.name

    class Meta:

        verbose_name = _('Изображение товара')
        verbose_name_plural = _('Изображения товаров')


class Order(models.Model):
    operation_region = models.CharField(max_length=255, verbose_name=_('Регион эксплуатации'), blank=True)
    client_type = models.CharField(max_length=255, choices=ClientTypeEnum.choices, default=ClientTypeEnum.LEGAL_ENTITY,
                                   verbose_name=_('От лица'))
    organization_full_name = models.CharField(max_length=255, verbose_name=_('Полное наименование организации'),
                                              blank=True)
    contact_person = models.CharField(max_length=255, verbose_name=_('Контактное лицо'), blank=True)
    phone_number = models.CharField(
        max_length=255, verbose_name=_('Номер телефона'))
    email = models.EmailField(verbose_name=_('Почта'), blank=True)
    chosen_product = models.ForeignKey(
        Product, on_delete=models.DO_NOTHING, related_name='orders')
    origin = models.CharField(max_length=255, choices=constants.OrderOriginEnum.choices, verbose_name=_('Источник'))
    comments = models.TextField(verbose_name=_('Комментарии'))
    is_handled = models.BooleanField(
        default=False, verbose_name=_('Обработан'))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Дата создания'))

    def __str__(self):
        return self.phone_number

    class Meta:
        verbose_name = _('Запрос КП')
        verbose_name_plural = _('Запросы КП')


class FAQ(models.Model):
    question = models.TextField(verbose_name=_('Вопрос'))
    answer = models.TextField(verbose_name=_('Ответ'))
    def __str__(self):
        return self.question

    class Meta:
        
        verbose_name = 'Часто задаваемый вопрос'
        verbose_name_plural = 'Часто задаваемые вопросы'


class Feedback(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Имя клиента'))
    company = models.CharField(max_length=255, verbose_name=_('Фирма'))
    feedback_text = models.TextField(verbose_name=_('Отзыв'))

    def __str__(self):
        return self.name

    class Meta:
        
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class ContactRequest(models.Model):
    phone_number = models.CharField(
        max_length=255, verbose_name=_('Номер телефона'))
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Дата создания'))
    info = models.TextField(
        max_length=500, verbose_name='Доп инфо', null=True, default=None)

    def __str__(self):
        return self.phone_number

    class Meta:
        
        verbose_name = 'Запрос на контакт'
        verbose_name_plural = 'Запросы на контакт'



def passgenerate():
    keys = '123456789qwertyuipasdfghjklzxcvbnmQWERTYUIPASDFGHJKLZXCVBNM'
    bit = 16
    bit2 = 0
    result = ''
    while bit > bit2:
        bit2 += 1
        result += random.choice(keys)
    return result

class Starter(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', unique=True, default='Нет')
    key = models.CharField(max_length=16, verbose_name='Ключ', unique=True, default=passgenerate)
    link = models.CharField(max_length=100, verbose_name='Ссылка', unique=True, default=f'https://t.me/UnimedStoreBot?start=')

    def __str__(self):
        self.link = self.link + self.key
        return self.name

    class Meta:
        verbose_name = 'Промоутеры'
        verbose_name_plural = 'Промоутеры'

def create_starter(sender, **kwargs):
    if kwargs['signal']:
        kwargs['instance'].link = str(kwargs['instance'].link) + str(kwargs['instance'].key)
pre_save.connect(create_starter, sender=Starter)


class Tuser(models.Model):
    userid = models.CharField(max_length=50, verbose_name='Telegram ID')
    step = models.CharField(max_length=5, verbose_name='Шаг', default=1)
    phone = models.CharField(max_length=14, verbose_name='Телефон', null=True, blank=True)
    prestep = models.CharField(max_length=5, verbose_name='Предыдущее действие', null=True)
    from_starter = models.ForeignKey(Starter, on_delete=models.CASCADE, null=True, verbose_name='Канал / Пришел')

    def __str__(self):
        return self.userid

    class Meta:
        verbose_name = 'Телеграм пользователь'
        verbose_name_plural = 'Телеграм пользователи'

website/models.py
from django.db import models

website/forms.py
from django import forms
from core.models import Order, ContactRequest


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('origin', 'comments', 'is_handled',
                   'created_at', 'chosen_product',)


class ContactRequestForm(forms.ModelForm):
    class Meta:
        model = ContactRequest
        exclude = ('created_at',)

website/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from core.models import *
from website.forms import OrderForm, ContactRequestForm
from telegram_bot.views import send_marketting_group
import json


class HomePage(TemplateView):
    template_name = 'pages/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ParentCategory.objects.all()
        context['faqs'] = FAQ.objects.all()
        context['feedbacks'] = Feedback.objects.all()
        return context

def ProductList(request):
    products = Product.objects.filter(name_search__icontains=request.GET.get('search').lower())
    context = {
        "products":products,
    }
    return render(request, "pages/products.html", context)


class CategoryListPage(ListView):
    model = ParentCategory
    template_name = 'pages/category-list.html'
    context_object_name = 'categories'


class CategoryDetailPage(DetailView):
    model = Category
    template_name = 'pages/category-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ParentCategory.objects.all()
        return context


class ProductDetailPage(DetailView):
    model = Product
    template_name = 'pages/product-detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ParentCategory.objects.all()
        return context


class ProductOrderPage(CreateView):
    form_class = OrderForm
    model = Order
    template_name = 'pages/order-page.html'
    success_url = '/orderSuccess/'

    def form_valid(self, form):
        form.instance.chosen_product = get_object_or_404(Product, slug=self.kwargs.get('slug'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ParentCategory.objects.all()
        context['product'] = get_object_or_404(Product, slug=self.kwargs.get('slug'))
        return context


class OrderSuccessPage(TemplateView):
    template_name = 'pages/order-success.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ParentCategory.objects.all()
        return context


class ContactRequestFormHandler(CreateView):
    model = ContactRequest
    form_class = ContactRequestForm
    success_url = '/contactRequestSuccess/'


class ContactRequestSuccessPage(TemplateView):
    template_name = 'pages/contact-request-success.html'



def Cooperate(request):
    form = ContactRequestForm
    context =  {
        "form": form
    }
    return render(request, 'core/cooperation.html', context)

@csrf_exempt
def Markettingmessage(request):
    if request.method == "POST":
        json_data = json.loads(request.body)
        send_marketting_group(json_data)
        return HttpResponse('200 OK')
    else:
        return HttpResponse('phone requried or send POST method')

website/templates/pages/category-detail.html
{% extends 'layouts/base.html' %}
{% block content %}
    <section class="container">
        <div class="category-heading py-5">
            <h1>{{ category.name }}</h1>
        </div>
        <div class="row align-items-stretch">
            {% for product in category.products.all %}
                <div class="col-12 col-md-4 py-3">
                    {% include 'components/product-block.html' with product=product %}
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

website/templates/pages/category-list.html
{% extends 'layouts/base.html' %}
{% block content %}
    <section class="container">
        {% for parent_category in categories %}
            <h1 class="pt-5">{{ parent_category.name }}</h1>
            {% for category in parent_category.child_categories.all %}
                <div class="category-block py-5">
                    <h2><a href="{% url 'category-detail' category.slug %}">{{ category.name }} <i class="fas fa-arrow-right"></i></a></h2>
                    <hr>
                    <div class="row align-items-stretch">
                        {% for product in category.products.all|slice:":3" %}
                            <div class="col-12 col-md-3">
                                {% include 'components/product-block.html' with product=product %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </section>
{% endblock content %}

website/templates/pages/contact-request-success.html
{% extends 'layouts/base.html' %}
{% block content %}
    <section class="container">
        <div class="py-5"></div>
        <section class="section-bg">
            <div class="container">
                <div class="section-title">
                    <h2>Запрос на звоное успешно принят!</h2>
                    <p class="pb-3">Спасибо, в скором времени мы обработаем ваш запрос и свяжемся используя данные введенные вами в форме.</p>
                    <a class="d-inline-flex align-items-center" href="{% url 'category-list' %}">Вернуться в каталог <i class='bx bxs-right-arrow-alt'></i></a>
                </div>

            </div>
        </section>
    </section>
{% endblock content %}

website/templates/pages/home.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block hero %}
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">
        <div class="container">
            <h1> БУ медицинское оборудование в Узбекистане</h1>
            <h2>Медицинская техника БУ в Узбекистане</h2>
            <a href="{% url 'category-list' %}" class="btn-get-started scrollto">Перейти в каталог</a>
        </div>
    </section><!-- End Hero -->
{% endblock hero %}

{% block content %}


    <!-- ======= Why Us Section ======= -->
    <section id="why-us" class="why-us">
        <div class="container-fluid container-xxl">

            <div class="row">
                <div class="col-xl-4 d-flex justify-content-center align-items-stretch">
                    <div class="content">
                        <h3>О нас</h3>
                        <p>
                            Комплексное оснащение медицинских учреждений с постоянной поддержкой на любой стадии сотрудничества Компания «Unimed Trade» обеспечивает поставки восстановленного и БУ оборудования от мировых производителей.
                        </p>
                        <div class="text-center">
                            <a href="{% url 'category-list' %}" class="more-btn">Посмотреть каталог <i
                                    class="bx bx-chevron-right"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-8 d-flex align-items-stretch">
                    <div class="icon-boxes d-flex flex-column justify-content-center">
                        <div class="row">
                            <div class="col-xl-4 d-flex align-items-stretch">
                                <div class="icon-box mt-4 mt-xl-0">
                                    <i class='bx bx-select-multiple'></i>
                                    <h4>Консультация</h4>
                                    <p>Мы поможем Вам сориентироваться в огромном выборе медицинского оборудования, которое будет отвечать всем Вашим заявленным требованиям, и подберем оптимальное оборудование соответствующее Вашему бюджету.</p>
                                </div>
                            </div>
                            <div class="col-xl-4 d-flex align-items-stretch">
                                <div class="icon-box mt-4 mt-xl-0">
                                    <i class='bx bx-line-chart'></i>
                                    <h4>Проекты под ключ</h4>
                                    <p> <b>Получение заявк</b>
                                        <br> Подбор оборудования с учетом всех требований заказчика 
                                        <br> <b>Выставление КП и подготовка к поставке оборудования</b> 
                                        <br> Доставка 
                                        <br> <b>Передача продукции </b>
                                        <br> Гарантийное и пост гарантийное обслуживание.</p>
                                </div>
                            </div>
                            <div class="col-xl-4 d-flex align-items-stretch">
                                <div class="icon-box mt-4 mt-xl-0">
                                    <i class='bx bx-money'></i>
                                    <h4>Рассрочка </h4>
                                    <p>У вас есть потребность в приобретении оборудования, но нет возможности осуществить 100% предоплату? 
                                        Мы готовы в режиме переговоров составить договор с приемлемым авансовым платежом с рассрочкой платежа до 2х лет. 
                                        Наша копания готова рассмотреть варианты финансирования и осуществит поставки любой сложности. </p>
                                </div>
                            </div>
                        </div>
                    </div><!-- End .content-->
                </div>
            </div>

        </div>
    </section><!-- End Why Us Section -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container-fluid">

            <div class="row">
                <!--<div class="col-xl-5 col-lg-6 video-box d-flex justify-content-center align-items-stretch position-relative">
                    <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox play-btn mb-4"></a>
                </div> -->
                <div class="col-xl-5 col-lg-6">
                    <video class="service-promo-video" autoplay muted loop src="{% static 'img/service-box-4.mp4' %}"></video>
                </div>

                <div class="col-xl-7 col-lg-6 icon-boxes d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5">
                    <h3>Насколько дешевле восстановленное медоборудование?</h3>
                    <p>Мы комплексно оснащаем медицинские учреждения c предоставлением гарантии на технику, обеспечиваем сервисное обслуживание оборудования. Восстановленное медоборудование в 2-5 раза дешевле нового, главное не купить "хлам", в чем наши эксперты вам помогут!</p>

                </div>
            </div>

        </div>
    </section><!-- End About Section -->


    <!-- ======= Services Section ======= -->
    <section id="services" class="services">
        <div class="container">

            <div class="section-title">
                <h2>Выгодные предложения</h2>
                <p></p>
            </div>

            <div class="row">
                <div class="col-12 col-md-4 py-3">
                    <video class="service-promo-video" autoplay muted loop src="{% static 'img/service-box-1.m4v' %}"></video>
                </div>
                <div class="col-12 col-md-4 py-3">
                    <video class="service-promo-video" autoplay muted loop src="{% static 'img/service-box-2.m4v' %}"></video>
                </div>
                <div class="col-12 col-md-4 py-3">
                    <video class="service-promo-video" autoplay muted loop src="{% static 'img/service-box-3.m4v' %}"></video>
                </div>
                <!--<div class="col-12 col-md-3 py-3">
                    <video class="service-promo-video" autoplay muted src="{% static 'img/service-box-4.mp4' %}"></video>
                </div>-->

            </div>

        </div>
    </section>




    <section id="faq" class="faq section-bg">
        <div class="container">

            <div class="section-title">
                <h2>Часто задаваемые вопросы</h2>
                <p>Если у вас возникли вопросы, которые вы не найдете здесь, вы всегда можете с нами связаться.</p>
            </div>

            <div class="faq-list">
                <ul>
                    {% for faq in faqs %}
                        <li data-aos="fade-up">
                            <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse"
                                                                           data-bs-target="#faq-list-{{ forloop.counter }}"
                                                                           class="collapsed">
                            {{ faq.question }}
                            <i class="bx bx-chevron-down icon-show"></i><i
                                class="bx bx-chevron-up icon-close"></i></a>
                            <div id="faq-list-{{ forloop.counter }}" class="collapse" data-bs-parent=".faq-list">
                                <p>
                                    {{ faq.answer }}
                                </p>
                            </div>
                        </li>
                    {% endfor %}

                </ul>
            </div>

        </div>
    </section>


    <section id="testimonials" class="testimonials">
        <div class="container">

            <div class="testimonials-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
                <div class="swiper-wrapper">

                    {% for feedback in feedbacks %}
                        <div class="swiper-slide">
                            <div class="testimonial-wrap">
                                <div class="testimonial-item">
                                    <h3>{{ feedback.name }}</h3>
                                    <h4>{{ feedback.company }}</h4>
                                    <p>
                                        <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                                        {{ feedback.feedback_text }}
                                        <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
                <div class="swiper-pagination"></div>
            </div>

        </div>
    </section><!-- End Testimonials Section -->


    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <div class="container">

            <div class="section-title">
                <h2>Связаться с нами</h2>
                <p>Мы рады сотрудничеству! Свяжитесь с нами заполнив форму снизу.</p>
            </div>
        </div>

        <div>
            <!-- <iframe style="border:0; width: 100%; height: 350px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d749.1445960081346!2d69.29367752926188!3d41.31803479870442!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef4d1f2e2ed7b%3A0xa1cf97f4cea98ef6!2sHamid%20Alimjan%20Square%2C%20Tashkent%2C%20Uzbekistan!5e0!3m2!1sen!2s!4v1617390993351!5m2!1sen!2s"
                    frameborder="0" allowfullscreen></iframe> -->
                    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A0d087970414862bb5a62b0a87caef1de5877d0ec7c0f56c57e2132edbef42091&amp;source=constructor" width="100%" height="350" frameborder="0"></iframe>     </div>
                    
        <div class="container">
            <div class="row mt-5">

                <div class="col-lg-4">
                    <div class="info">
                        <div class="address">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Адрес:</h4>
                            <p>г.Ташкент. Юнус Абадский р-н, Малая кольцевая дорога 26 </p>
                        </div>

                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <h4>Почта:</h4>
                            <p>info@unimedtrade.uz</p>
                        </div>

                        <div class="phone">
                            <i class="bi bi-phone"></i>
                            <h4>Телефон:</h4>
                            <p>+998(71)200-44-04</p>
                        </div>

                    </div>

                </div>

                <div class="col-lg-8 mt-5 mt-lg-0 d-flex justify-content-center align-items-center">

                    <form action="{% url 'contact-request' %}" method="post" role="form" class="php-email-form">
                        {% csrf_token %}
                        <div class="row justify-content-center">
                            <div class="col-12 col-md-5">
                                <div class="py-5">
                                    <input class="form-control"  type="text" name="phone_number" maxlength="255" required
                                           id="id_phone_number" placeholder="Номер телефона">
                                </div>
                                <div class="text-center">
                                    <button type="submit">Заказать звонок</button>
                                </div>
                            </div>
                        </div>


                    </form>

                </div>

            </div>

        </div>
    </section><!-- End Contact Section -->

{% endblock content %}

website/templates/pages/order-page.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="container">
        <div class="py-5"></div>
        <section class="section-bg">
            <div class="container">
                <div class="section-title">
                    <h2>Запросить коммерческое предложение</h2>
                    <p>Для того чтобы запросить коммерческое предложение для продукта "{{ product.name }}"
                        пожалуйста,
                        заполните форму ниже.</p>
                </div>
                <div class="form-wrapper row justify-content-center">
                    <div class="col-12 col-md-4">
                        <form id="product-order-form" action="{% url 'product-order' product.slug %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div>
                                <button type="submit">Запросить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock content %}

website/templates/pages/order-success.html
{% extends 'layouts/base.html' %}
{% block content %}
    <section class="container">
        <div class="py-5"></div>
        <section class="section-bg">
            <div class="container">
                <div class="section-title">
                    <h2>Запрос успешно принят!</h2>
                    <p class="pb-3">Спасибо, в скором времени мы обработаем ваш запрос и свяжемся используя данные введенные вами в форме.</p>
                    <a class="d-inline-flex align-items-center" href="{% url 'category-list' %}">Вернуться в каталог <i class='bx bxs-right-arrow-alt'></i></a>
                </div>

            </div>
        </section>
    </section>
{% endblock content %}

website/templates/pages/products.html
{% extends 'layouts/base.html' %}
{% block content %}

<h1 class="mt-5"></h1> <br><br>
<div class="row">



{% for i in  products%}

<div class="col-12 col-md-4 py-3">
    {% include 'components/product-block.html' with product=i %}
</div>
{% endfor %}
</div>
{% endblock %}